using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Avalonia.Controls;

namespace ICSharpCode.ILSpy.Metadata
{
	/// <summary>
	/// Interaction logic for MetadataTableViews.xaml
	/// </summary>
	public partial class MetadataTableViews : ResourceDictionary
	{
		public MetadataTableViews()
		{
			InitializeComponent();
		}

		static MetadataTableViews instance;

		public static MetadataTableViews Instance {
			get {
				if (instance == null)
				{
					instance = new MetadataTableViews();
				}
				return instance;
			}
		}

		private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			Helpers.View_AutoGeneratedColumns(sender, e);
		}

		private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			Helpers.View_AutoGeneratingColumn(sender, e);
		}
	}
}
